### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by Daudi88**

### CODE REVIEW

**Review by Daudi88 — COMMENTED** [review]
Looks good

**Review by Malmsteg — COMMENTED** [review]
Ser fint ut, hittar inget att anmärka på 😍

**Review by myrlejon — APPROVED** [review]
Ser inte ut att vara några problem, grönt ljus!

**Review by jerry1938 — CHANGES_REQUESTED** [review]
1.  Each child in a list should have a unique "key" prop. Felet verkar vara i DetailsCard

2. Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

3. TypeError: Cannot read properties of null (reading 'id') 

4.  DisplayLoading.js - finns bortkommenterad kod.

5. DisplayListOfPokemon.js - finns bortkommenterad kod.

6. DisplayData - finns bortkommenterad kod.

7. DetailsView.js - saknar kommentarer.

8. PokemonProvide.js - saknar kommentarer.

9. src/components/cardTitle/CardTitle.js
  Line 1:17:  'useState' is defined but never used  no-unused-vars

10. src/shared/provider/PokemonProvider.js
  Line 92:6:  React Hook useEffect has a missing dependency: 'allPokemon'. Either include it or remove the dependency array. You can also do a functional update 'setAllPokemon(a => ...)' if you only need 'allPokemon' in the 'setAllPokemon' call  react-hooks/exhaustive-deps

11. src/views/homeview/HomeView.js
  Line 37:6:  React Hook useEffect has a missing dependency: 'getFirstPokemon'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Review by jerry1938 — APPROVED** [review]
Ser bra ut nu.

**Review by emilorjes — APPROVED** [review]
Ser bra ut :)

**Review by samwon66 — APPROVED** [review]
Look really good

**Pull request merged**
